// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "installation.mdx": () => import("../content/docs/installation.mdx?collection=docs"), "privacy.mdx": () => import("../content/docs/privacy.mdx?collection=docs"), "api/index.mdx": () => import("../content/docs/api/index.mdx?collection=docs"), "cloud/alerts.mdx": () => import("../content/docs/cloud/alerts.mdx?collection=docs"), "cloud/api-access.mdx": () => import("../content/docs/cloud/api-access.mdx?collection=docs"), "cloud/getting-started.mdx": () => import("../content/docs/cloud/getting-started.mdx?collection=docs"), "cloud/monitoring.mdx": () => import("../content/docs/cloud/monitoring.mdx?collection=docs"), "api/collections/createCollection.mdx": () => import("../content/docs/api/collections/createCollection.mdx?collection=docs"), "api/collections/deleteCollection.mdx": () => import("../content/docs/api/collections/deleteCollection.mdx?collection=docs"), "api/collections/getCollection.mdx": () => import("../content/docs/api/collections/getCollection.mdx?collection=docs"), "api/collections/listCollections.mdx": () => import("../content/docs/api/collections/listCollections.mdx?collection=docs"), "api/collections/updateCollection.mdx": () => import("../content/docs/api/collections/updateCollection.mdx?collection=docs"), "api/endpoints/createEndpoint.mdx": () => import("../content/docs/api/endpoints/createEndpoint.mdx?collection=docs"), "api/endpoints/deleteEndpoint.mdx": () => import("../content/docs/api/endpoints/deleteEndpoint.mdx?collection=docs"), "api/endpoints/getEndpoint.mdx": () => import("../content/docs/api/endpoints/getEndpoint.mdx?collection=docs"), "api/endpoints/listEndpoints.mdx": () => import("../content/docs/api/endpoints/listEndpoints.mdx?collection=docs"), "api/endpoints/updateEndpoint.mdx": () => import("../content/docs/api/endpoints/updateEndpoint.mdx?collection=docs"), "api/monitoring/createAlert.mdx": () => import("../content/docs/api/monitoring/createAlert.mdx?collection=docs"), "api/monitoring/listAlerts.mdx": () => import("../content/docs/api/monitoring/listAlerts.mdx?collection=docs"), "api/monitoring/listRequests.mdx": () => import("../content/docs/api/monitoring/listRequests.mdx?collection=docs"), "api/sync/getSyncStatus.mdx": () => import("../content/docs/api/sync/getSyncStatus.mdx?collection=docs"), "api/sync/syncCollection.mdx": () => import("../content/docs/api/sync/syncCollection.mdx?collection=docs"), }),
};
export default browserCollections;