// @ts-nocheck
import * as __fd_glob_44 from "../content/docs/api/sync/syncCollection.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/api/sync/getSyncStatus.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/api/monitoring/monitoring-sendRequest.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/api/monitoring/monitoring-getUptimeStats.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/api/monitoring/monitoring-getUptimeChart.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/api/monitoring/monitoring-getTopEndpoints.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/api/monitoring/monitoring-getResponseTimeHistory.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/api/monitoring/monitoring-getResponseTimeChart.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/api/monitoring/monitoring-getRecentFailures.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/api/monitoring/monitoring-getHistory.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/api/monitoring/monitoring-getAverageResponseTime.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/api/monitoring/monitoring-getAnalytics.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/api/monitoring/monitoring-checkEndpoint.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/api/collection/collection-updateCollection.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/api/collection/collection-searchCollections.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/api/collection/collection-getMyCollections.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/api/collection/collection-getCollectionStats.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/api/collection/collection-getCollection.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/api/collection/collection-duplicateCollection.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/api/collection/collection-deleteCollection.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/api/collection/collection-createCollection.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/api/api-endpoint/apiEndpoint-verify.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/api/api-endpoint/apiEndpoint-updateOverrides.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/api/api-endpoint/apiEndpoint-update.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/api/api-endpoint/apiEndpoint-getEndpoints.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/api/api-endpoint/apiEndpoint-get.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/api/api-endpoint/apiEndpoint-delete.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/api/api-endpoint/apiEndpoint-create.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/api/api-endpoint/apiEndpoint-bulkVerify.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/api/alert/alert-update.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/api/alert/alert-getByEndpoint.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/api/alert/alert-delete.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/api/alert/alert-create.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/cloud/monitoring.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/cloud/getting-started.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/cloud/api-access.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/cloud/alerts.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/api/index.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/privacy.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/installation.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/index.mdx?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/api/sync/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/cloud/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/api/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "api/meta.json": __fd_glob_1, "cloud/meta.json": __fd_glob_2, "api/sync/meta.json": __fd_glob_3, }, {"index.mdx": __fd_glob_4, "installation.mdx": __fd_glob_5, "privacy.mdx": __fd_glob_6, "api/index.mdx": __fd_glob_7, "cloud/alerts.mdx": __fd_glob_8, "cloud/api-access.mdx": __fd_glob_9, "cloud/getting-started.mdx": __fd_glob_10, "cloud/monitoring.mdx": __fd_glob_11, "api/alert/alert-create.mdx": __fd_glob_12, "api/alert/alert-delete.mdx": __fd_glob_13, "api/alert/alert-getByEndpoint.mdx": __fd_glob_14, "api/alert/alert-update.mdx": __fd_glob_15, "api/api-endpoint/apiEndpoint-bulkVerify.mdx": __fd_glob_16, "api/api-endpoint/apiEndpoint-create.mdx": __fd_glob_17, "api/api-endpoint/apiEndpoint-delete.mdx": __fd_glob_18, "api/api-endpoint/apiEndpoint-get.mdx": __fd_glob_19, "api/api-endpoint/apiEndpoint-getEndpoints.mdx": __fd_glob_20, "api/api-endpoint/apiEndpoint-update.mdx": __fd_glob_21, "api/api-endpoint/apiEndpoint-updateOverrides.mdx": __fd_glob_22, "api/api-endpoint/apiEndpoint-verify.mdx": __fd_glob_23, "api/collection/collection-createCollection.mdx": __fd_glob_24, "api/collection/collection-deleteCollection.mdx": __fd_glob_25, "api/collection/collection-duplicateCollection.mdx": __fd_glob_26, "api/collection/collection-getCollection.mdx": __fd_glob_27, "api/collection/collection-getCollectionStats.mdx": __fd_glob_28, "api/collection/collection-getMyCollections.mdx": __fd_glob_29, "api/collection/collection-searchCollections.mdx": __fd_glob_30, "api/collection/collection-updateCollection.mdx": __fd_glob_31, "api/monitoring/monitoring-checkEndpoint.mdx": __fd_glob_32, "api/monitoring/monitoring-getAnalytics.mdx": __fd_glob_33, "api/monitoring/monitoring-getAverageResponseTime.mdx": __fd_glob_34, "api/monitoring/monitoring-getHistory.mdx": __fd_glob_35, "api/monitoring/monitoring-getRecentFailures.mdx": __fd_glob_36, "api/monitoring/monitoring-getResponseTimeChart.mdx": __fd_glob_37, "api/monitoring/monitoring-getResponseTimeHistory.mdx": __fd_glob_38, "api/monitoring/monitoring-getTopEndpoints.mdx": __fd_glob_39, "api/monitoring/monitoring-getUptimeChart.mdx": __fd_glob_40, "api/monitoring/monitoring-getUptimeStats.mdx": __fd_glob_41, "api/monitoring/monitoring-sendRequest.mdx": __fd_glob_42, "api/sync/getSyncStatus.mdx": __fd_glob_43, "api/sync/syncCollection.mdx": __fd_glob_44, });